language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy3.5"
  - "pypy3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pyyaml toml
  - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter # for codeclimate-test-reporter
script:
  - bash tests/test_posix/test_hang_until_sig.sh
  - python setup.py test
after_success:
  - codeclimate-test-reporter
  - bash build.sh
