language: python
python:
 - "3.5"
 - "3.6"
 - "3.7-dev"
 - "pypy3.5"
cache: pip
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter # for codeclimate-test-reporter
script:
 - bash tests/test_posix/test_hang_until_sig.sh
 - python setup.py nosetests
after_success:
 - codeclimate-test-reporter
 - bash build.sh
